### ISSUE TITLE
This PREFIXSHORTCUT is not consistent.

### ISSUE THREAD

**Issue by romeojulietthotel** [gillesdegottex/fmit#107]
https://github.com/gillesdegottex/fmit/blob/0a2c9b90ec92ed6920a2b90c79b28e24162d7323/fmit.pro#L48

If not PREFIX is specified by the user then it is `/usr/local` but still the fmit.desktop file gets installed into `/usr` instead of `/usr/local`.

It should be the same as PREFIX and PREFIXSHORTCUT is not needed I think.

**Comment by gillesdegottex** [comment]
Thanks for the feedback.
I remember to have done this on purpose, but now I can't remember the reason and, of course, I didn't leave a note... Let me think of it.

**Comment by romeojulietthotel** [comment]
There is this commit:
https://github.com/gillesdegottex/fmit/commit/01f9f790fbc70920369b0e37c3f479a939e12b85

It is an install idiom that if you use `/usr` then all files get installed with `/usr` as the root destination (or PREFIX or INSTALL_ROOT, etcetera). So `/usr/local` or `/opt` would adhere to the same idiom.

It's also an idiom that you can place files wherever you'd like to but that involves a deliberate setting. Without a deliberate setting then the default is used.

**Comment by gillesdegottex** [comment]
So, by default, PREFIXSHORTCUT should be set to PREFIX, except if PREFIXSHORTCUT is set to something specific, right?

**Comment by romeojulietthotel** [comment]
Oui.
