### ISSUE TITLE
weblate and github are not sync

### ISSUE THREAD

**Issue by trebmuh** [gillesdegottex/fmit#110]
See https://github.com/gillesdegottex/fmit/pull/109#issuecomment-397628277

**Comment by dsboger** [comment]
I think they are in sync now. There was a delay, but it ended up sync'ing a few hours later. Could you confirm that (i.e. check that your latest translation was pushed)?

**Comment by trebmuh** [comment]
You seems to be right. Everything looks all good.
Closing then.
