### ISSUE TITLE
Closing main window doesn't close configuration window (if it was open).

### ISSUE THREAD

**Issue by dwrobel** [gillesdegottex/fmit#115]
I've just updated fmit package on Fedora to [v1.2.6](https://src.fedoraproject.org/rpms/fmit/blob/master/f/fmit.spec#_3) and noticed that there seems be an issue as described in the title.

The interesting thing is that my e-mail history _(I hope your @gillesdegottex  might also)_ remember this issue being reported in 2011 _(a pre github fmit era)_:

>  ---- On Fri, 28 Jan 2011 08:33:11 +0100 Damian Wrobel <dwrobel@ertelnet.rybnik.pl> wrote ---- 
> > Done: 0.99.2.
>
> I've prepared a package and one guy during the testing has found the 
> following small issue: 
>  
> -Start FMIT and open the configuration window 
> -Close FMIT 
> -The configuration windows stays alive

**Comment by gillesdegottex** [comment]
I remember a similar behavior on another app I've developed.
It should be easy to fix. I'll try to do it whenever I got a bit of time.
Thanks for this report!

**Comment by trebmuh** [comment]
Confirmed here (version 1.2.6) on a Debian Stretch.

**Comment by gillesdegottex** [comment]
Bug easily reproduced on my side, and fixed.
Please re-open if it persists.
