### ISSUE TITLE
Strange release text for 1.2.13

### ISSUE THREAD

**Issue by trebmuh** [gillesdegottex/fmit#123]
Salut @gillesdegottex.

On [the github 1.2.13 release](https://github.com/gillesdegottex/fmit/releases), the text is exactly the same than for 1.2.6. Is that expected or something went wrong?

**Comment by gillesdegottex** [comment]
Yes, it is only small patches that does not change the overall modifications brought by 1.2

**Comment by trebmuh** [comment]
OK, no worries. Closing here then.
