### ISSUE TITLE
License issues

### ISSUE THREAD

**Issue by badshah400** [gillesdegottex/fmit#130]
Trying to package fmit for openSUSE, but our licence checker identifies the following issues (see [request 806782]), making it difficult to have one consistent License tag in the RPM specfile. I have `GPL-2.0-only` for now but that will have to change.

```

    Any reference local: 1 files
        fmit-1.2.13/distrib/fmit.1
    GPL-3.0+: 2 files
        fmit-1.2.13/src/aboutbox.h
        fmit-1.2.13/src/aboutbox.processed.cpp
    GPL-Unspecified: 3 files
        fmit-1.2.13/README.processed.txt
        fmit-1.2.13/src/aboutbox.h
        fmit-1.2.13/src/aboutbox.processed.cpp

    GPL-2.0+: 21 files
    LGPL-3.0+: 1 files
        fmit-1.2.13/src/qthelper.processed.h
```

It would be useful if the source code could be licensed consistently, perhaps as LGPL-2.1-or-later (for the libraries) and GPL-3.0-or-later for the app. If that doesn't work for you, I would be grateful if you could suggest something else to resolve the licensing issues flagged in [request 806782].

Thank you.

[request 806782]: https://build.opensuse.org/request/show/806872

**Comment by gillesdegottex** [comment]
Thx for this analysis!
This should be (L)GPL-3.0
I'll change the license boilerplates asap.

**Comment by gillesdegottex** [comment]
I just thought about it again:
That's not possible to tag a package with a unique license most of the time since most softwares are made of various components that are likely to have different licenses.

So I don't really get the point.

I'll replace the GPL-Unspecified to GPL-3.0+ though, and see if I can replace GPL-2.0+ by GPL-3.0+ too.

Cheers,

**Comment by gillesdegottex** [comment]
>         fmit-1.2.13/src/aboutbox.h
>         fmit-1.2.13/src/aboutbox.processed.cpp
v3 is indicated in the text, this not "GPL-Unspecified".

**Comment by gillesdegottex** [comment]
Done.

Everything should be under v2 now.

Cheers,

**Comment by badshah400** [comment]
Many thanks, I submitted the updated version <https://build.opensuse.org/request/show/822864>
