### ISSUE TITLE
The build instructions are outdated

### ISSUE THREAD

**Issue by dsboger** [gillesdegottex/fmit#26]
Hello, I am trying to update `fmit` package on Archlinux User Repository (https://aur.archlinux.org/), but I'm facing a few issues. First, I tried to follow the build instructions in `INSTALL.txt`, but they do not work anymore. I figured out how to build with `qmake` by inspecting other files. My current build script is as follows:

    qmake-qt5 "CONFIG+=acs_qt acs_alsa acs_jack acs_portaudio" fmit.pro
    make

It seems to work, but the about screen informs a strange version number:

![fmit-about-error](https://cloud.githubusercontent.com/assets/2356842/9156048/1d50c946-3ea3-11e5-8ffb-48a018d719db.png)

By reading the code it seems the version number is taken from the `README.txt` file, so probably I'm not installing it to the right place. Also, I don't know what to do with the files in `tr` and `scales` folders.

Lastly, I'm not sure what are the current dependencies (required or optional), as these seem to have changed recently from what is described in `INSTALL.txt`.

Please, let me know if I can help somehow. Thanks.

**Comment by gillesdegottex** [comment]
Hello !

Thanks for telling me about the INSTALL.txt file ! I updated it.
I also added installation instructions for qmake, with the paths where the translations and the scales should go.

The README.txt is included in the resource file fmit.qrc, so as long as this resource file is properly compiled, this version should appear properly. I might have forgot to add this resource file in the previous version. It is there now, for sure. Tell me if this problem still appear.

Can you try the new release v1.0.6 and tell me if everything's fine ?

**Comment by dsboger** [comment]
I managed to build and install properly, except that I had to install the icon and appdata files "by hand", not sure if it is intended.

As for the version number, I found that in file `CustomInstrumentTunerForm.cpp`, line 1053, changing `":/README.txt"` to `":/fmit/README.txt"` solves part of the issue. Furthermore, it seems the "parsing" of the version number is not in sync with the current `README.txt` formatting (it must skip one extra line and the word "Version" is duplicated).

**Comment by gillesdegottex** [comment]
*Ouch*, the resource path were wrong. Fixed in the master.

The desktop (icon) file goes here:
/usr/share/applications/fmit.desktop
no ?

where goes the appdata ?

**Comment by dsboger** [comment]
Yes, desktop file is ok. I mean the icon images (`ui/images/fmit.svg` and `ui/images/fmit.png`), which should be installed as (respectively)

    $$PREFIX/share/icons/hicolor/scalable/apps/fmit.svg
    $$PREFIX/share/icons/hicolor/128x128/apps/fmit.png

`distrib/fmit.appdata.xml` should be installed as

    $$PREFIX/share/appdata/fmit.appdata.xml

**Comment by gillesdegottex** [comment]
Fixed on the master.

**Comment by dsboger** [comment]
Installation is perfect! Thanks for your great work.

Only a minor glitch remains: "Version" word is duplicated in the about dialog. I'll close this bug anyway, as that the main issue is fixed! Thanks again.

**Comment by gillesdegottex** [comment]
Thanks for your feedbacks !

The duplicated Version word should be fixed now.

**Comment by dsboger** [comment]
Great! Already pushed the package to AUR [1]. Also added a "git" version that always updates to the latest commit [2].

[1] https://aur.archlinux.org/packages/fmit
[2] https://aur.archlinux.org/packages/fmit-git
