### ISSUE TITLE
Cannot use ASIO audio interface on Windows 7 x64

### ISSUE THREAD

**Issue by Megal** [gillesdegottex/fmit#33]
On Configuration->Capture System tab
I don't have my default audio interface in "Device Name" list.

I'm using Saffire firewire audio interface in 44.1kHz/24bit sample format mode. It has 16 input channels and 8 output. Applications normally use 1-2 input and 1-2 output channels if they don't have good ASIO support.

**Comment by gillesdegottex** [comment]
I think there is a problem with 24b (see #3)

Could you try configure your ASIO with 16b just to see if this is working ?

**Comment by Megal** [comment]
Was issue on my side. 16 bit and 24 bit both works.

**Comment by gillesdegottex** [comment]
How is that possible, I'm quite sure FMIT cannot manage 24b
(there is only conversion for 8bits and 16bits in the first lines of https://github.com/gillesdegottex/fmit/blob/master/src/CaptureThread.cpp)

Out of curiosity, could you just run FMIT on command line and tell me the output ?
(like what's coming after "CaptureThread: INFO: format is ..." )
