### ISSUE TITLE
Immediate crash with lowlatency kernel

### ISSUE THREAD

**Issue by FMITBugReport** [gillesdegottex/fmit#35]
Both the FMIT versions from the Ubuntu 14.04LTS repository (Version 0.99.2) and a self-built from the source code (Version 1.0.12) crash when used with the low-latency kernel 3.13.0.68.74 (also from the 14.04LTS repository). The program window opens and shows correctly, but then immediately freezes. Only killing the process is possible. No problem occurs with the generic kernel 3.11.0-12. - It is a 32 bit system.

**Comment by gillesdegottex** [comment]
For reason of time, I'm afraid I cannot investigate more on this soon.
Could you try another qt5-opengl application ?

**Comment by FMITBugReport** [comment]
Hi,

Sure I can try - if you can suggest one that I can pull from the Ubuntu
14.04 repositories. I am not sure how to identify an qt5-opengl application.

Cheers, Oliver.

**Comment by gillesdegottex** [comment]
You can start with the package qtbase5-example
Then run some of the examples, for example:
/usr/lib/i386-linux-gnu/qt5/examples//opengl/2dpainting/2dpainting
/usr/lib/i386-linux-gnu/qt5/examples/opengl/paintedwindow/paintedwindow
/usr/lib/i386-linux-gnu/qt5/examples/opengl/overpainting/overpainting

This one is also qt5-opengl, but you have to compile it. It is one of my project that I'm currently developing (i.e. if you crash this one, I'll be quite motivated to dig into the problem ;) )
Try:
$ git clone https://github.com/gillesdegottex/dfasma.git
$ cd dfasma
$ qmake dfasma.pro
$ make

This one is also qt5-opengl: http://www.sonicvisualiser.org/
Package: sonic-visualiser

**Comment by FMITBugReport** [comment]
Hi,

So sonic-visualiser (from Ubuntu 14.04 repos) runs equally well with the
generic and the low-latency kernel.

The qtbase5-example have funny graphics artefacts, but it is again the
same with both the generic and the low-latency kernel.

I just started using the low latency kernel a little while ago, but
except with FMIT I noticed no difference with any other programs I use.

In any case, it is no big deal for me that FMIT does not work with this
kernel, but still it  would be nice if eventually this can be fixed. It
is a really nice feature-rich tuner.

Cheers, Oliver.

**Comment by gillesdegottex** [comment]
glut dependency has been removed, it could be worth trying the latest release.

**Comment by FMITBugReport** [comment]
Hi,

I just checked the FMIT version (Version 1.0.0) from the Xubuntu 16.04 
LTS repository, Kernel 4.4.0-21-lowlatency.

No more crash, runs normal.

Cheers, Oliver.

**Comment by gillesdegottex** [comment]
Yeahhh, dependency removal, the best bug spray in coding history.
