### ISSUE TITLE
I am using fmit to find out notes I whistle, but how to log results?

### ISSUE THREAD

**Issue by ninuzzo** [gillesdegottex/fmit#36]
Hi, I am a beginner songwriter and would want to find out notes I whistle. fmit does a very good job in doing that, but I can't get any record of the notes. Since my whistle is fast, I can't see and remember them all. It is difficult for me to slow down my whistle too much and keep the same pitch as the normal version. Is there a way to get or enable a log? I was just to log stuff like G3, F#6 and so on, but if there are more info in the log, no problem for me to just extract what I need, e.g. using AWK or similar.

**Comment by gillesdegottex** [comment]
That would be a nice feature definitely.
Maybe save the history of notes into a MIDI file.
Unfortunately I don't have time to implement this soon.

In the meantime you can enable the "Keep" button on the left. It will keep the previous notes you whistled, but there is nothing to drop the notes in any file currently.

**Comment by ninuzzo** [comment]
Hi Gilles,
At last I ended up learning how to do it by ear on the guitar. This is very
important, one does not have to fear it. Anyway, it would certainly be a
nice feature for songwriters wanting to check their note guesses to let the
computer do it. I am a programmer too, but now I do not have time to study
your code and change it  because I am studing music and writing songs :-)

**Comment by gillesdegottex** [comment]
Yhea, if you can do it by ears, that's even better ;)

**Comment by gillesdegottex** [comment]
That's more like automatic transcription, which is a bit off for FMIT's purpose.
Maybe somewhat can do it one day, if there is more requests.
Closing in the meantime.
