### ISSUE TITLE
Windows: error 0xc000007b

### ISSUE THREAD

**Issue by Omega9** [gillesdegottex/fmit#37]
![clipboard01](https://cloud.githubusercontent.com/assets/355689/14297338/aed7c264-fb97-11e5-86c8-f599c8d06bb8.png)
FMIT crashes on start with 0xc000007b
Windows 8.1 x64

**Comment by gillesdegottex** [comment]
Dear lord ... is there any way to have more details ?
I don't have a Windows 8.1 to test this.

Is it possible to check the availabilities of the dll ? (e.g. using dependencywalker)
Do you feel like installing Qt Creator on your machine and compile FMIT in debug mode and run it to see where it crashes ? ...

Thanks for your feedback though.

**Comment by Omega9** [comment]
Not sure if I did it right.

```
Starting profile on 13.04.2016 at 22:45:37

Operating System: Microsoft Windows NT/2000/XP/2003/Vista based Enterprise (64-bit), version 6.02.9200
Program Executable: c:\program files\fmit\FMIT.EXE
Program Arguments: 
Starting Directory: C:\Program Files\FMIT\
Search Path: C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\ia32\compiler;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\ProgramData\chocolatey\bin;C:\Program Files\Java\jre1.8.0_66\bin;C:\Program Files (x86)\GTK2-Runtime\bin;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files\Git\cmd;C:\Program Files (x86)\GitExtensions\;C:\Program Files\Java\jre1.8.0_71\bin;C:\Program Files\Java\jre1.8.0_73\bin;C:\Program Files (x86)\Skype\Phone\;C:\Users\Omega9\appdata\local\scoop\shims;C:\Users\Omega9\AppData\Local\atom\bin;C:\tools\cmder;

Options Selected:
     Simulate ShellExecute by inserting any App Paths directories into the PATH environment variable.
     Log DllMain calls for process attach and process detach messages.
     Hook the process to gather more detailed dependency information.
     Log LoadLibrary function calls.
     Log GetProcAddress function calls.
     Log debug output messages.
     Automatically open and profile child processes.
--------------------------------------------------------------------------------

Started "FMIT.EXE" (process 0x79C) at address 0x00007FF7C35A0000.  Successfully hooked module.
Loaded "NTDLL.DLL" at address 0x00007FFF0B3A0000.  Successfully hooked module.
Loaded "KERNEL32.DLL" at address 0x00007FFF09810000.  Successfully hooked module.
Loaded "KERNELBASE.DLL" at address 0x00007FFF08AD0000.  Successfully hooked module.
DllMain(0x00007FFF08AD0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "KERNELBASE.DLL" called.
DllMain(0x00007FFF08AD0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "KERNELBASE.DLL" returned 1 (0x1).
DllMain(0x00007FFF09810000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "KERNEL32.DLL" called.
DllMain(0x00007FFF09810000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "KERNEL32.DLL" returned 1 (0x1).
Injected "DEPENDS.DLL" at address 0x0000000068DE0000.
DllMain(0x0000000068DE0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "DEPENDS.DLL" called.
DllMain(0x0000000068DE0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "DEPENDS.DLL" returned 1 (0x1).
Loaded "OPENGL32.DLL" at address 0x00007FFEF5D50000.  Successfully hooked module.
Loaded "LIBFFTW3-3.DLL" at address 0x0000000070680000.  Successfully hooked module.
Loaded "FREEGLUT.DLL" at address 0x000000005FCF0000.  Successfully hooked module.
Loaded "FREEGLUT.DLL" at address 0x0000000000630000.  Successfully hooked module.
Unloaded "FREEGLUT.DLL" at address 0x0000000000630000.
Unloaded "FREEGLUT.DLL" at address 0x000000005FCF0000.
Exited "FMIT.EXE" (process 0x79C) with code -1073741701 (0xC000007B).
```

**Comment by gillesdegottex** [comment]
Sorry, it doesn't tell me much. Except that the issue seems to come from FMIT itself.

Did you install the installer that is available here ? Or did you recompiled it ?
(it might be worth trying to recompile it in a Windows8 environment.)

Thanks for the investigation !

**Comment by Omega9** [comment]
I've used installer.
I can't install too much software on that Windows PC, sorry.

Someone told me that 0xc000007b may be caused by video drivers or DirectX and it's not a rare thing for gamers.

**Comment by gillesdegottex** [comment]
I see that freeglut is still loaded. So according to what you say, we have a small chance that it is solved when I get ride of freelgut in FMIT. This is already planned, but it will take a bit of time and I don't have much of this thing these days :(
Maybe this summer, I hope.

**Comment by lupinia** [comment]
I'm having the exact same issue on Windows 7, so this doesn't appear to be Windows 8 specific.

**Comment by gillesdegottex** [comment]
Well, I got one extra motivation for doing this now :)
Thanks guys for the feedback!

**Comment by gillesdegottex** [comment]
There is a new build, can you try it ? (more out of curiosity than a strong hope to fix this...)

https://ci.appveyor.com/api/buildjobs/f9agxedcalpto3df/artifacts/FMIT-v1.0.12-3-g227ed8d-Win64bit.exe

**Comment by Omega9** [comment]
Same error.

**Comment by gillesdegottex** [comment]
Can you try this software ?
https://github.com/gillesdegottex/dfasma/releases
In order to test it, just load a short wav file.

(if this one works, FMIT will work when I'll remove the GLUT dependency)

**Comment by Omega9** [comment]
Already tried. Works fine!

**Comment by gillesdegottex** [comment]
Great, so there is some hope here ;)
Thanks a lot for your feedback!

**Comment by gillesdegottex** [comment]
Done!

Any of you can try this ?
https://ci.appveyor.com/project/gillesdegottex/fmit/build/1.0.81/artifacts

**Comment by Omega9** [comment]
That error's gone, but there's another one:
![error](https://cloud.githubusercontent.com/assets/355689/14779729/fa464986-0af2-11e6-9bdf-45141189578c.png)

**Comment by gillesdegottex** [comment]
Great !

Can you try with a different sound card ? (e.g. the internal one)

**Comment by gillesdegottex** [comment]
(can you open a new issue with this error actually ? thanks)

**Comment by Omega9** [comment]
Done

**Comment by gillesdegottex** [comment]
thanks!
