### ISSUE TITLE
Missing fmit.desktop and fmit.appdata.xml

### ISSUE THREAD

**Issue by geertpeeters** [gillesdegottex/fmit#4]
Managed to build this interesting application on Antergos.
fmit.desktop and fmit.appdata.xml however should reside in de unzipped root directory of fmit.
I simply touched both to make th make install pass.
I'm planning to try this out for tuning a historic reed organ.
Hope it's accurate enough to do the job.
Edit : I tried some sound samples sending to your application. It is truly a very handy and powerful piece of software. Great work, well done! Thanks for sharing

**Comment by gillesdegottex** [comment]
Hi thanks for the feedback,

Could you tell me why is it necessary to have these files in the root directory ?

The file paths are maybe not properly set in the cmake file.

Cheers

**Comment by Omega9** [comment]
There's two strings in CMakeLists.txt:
```
# Desktop files
INSTALL(FILES
  fmit.desktop
  DESTINATION share/applications
)

# AppData file
INSTALL(FILES
  fmit.appdata.xml
  DESTINATION share/appdata
)
```

which need to be changed to:
```
# Desktop files
INSTALL(FILES
  distrib/fmit.desktop
  DESTINATION share/applications
)

# AppData file
INSTALL(FILES
  distrib/fmit.appdata.xml
  DESTINATION share/appdata
)
```

**Comment by gillesdegottex** [comment]
Great ! Thanks !
