### ISSUE TITLE
Windows: Error Qt Cannot open device

### ISSUE THREAD

**Issue by Omega9** [gillesdegottex/fmit#43]
![](https://cloud.githubusercontent.com/assets/355689/14779729/fa464986-0af2-11e6-9bdf-45141189578c.png)

I've got this with EMU 0404 USB on Win8.1 x64.
Two other guys tried to run FMIT with M-Audio ProFire 2626 and integrated soundcard. They got same error.

**Comment by gillesdegottex** [comment]
Is there any cyrillic characters in this name?
(like in the device list of your OS, or another audio software)

**Comment by Omega9** [comment]
Sorry for delay.
No, it's just "E-MU 0404 | USB" in the device manager.

**Comment by gillesdegottex** [comment]
How is the list of devices in the configuration panel ?

**Comment by gillesdegottex** [comment]
There might be a fix in this one:
https://ci.appveyor.com/project/gillesdegottex/fmit/build/1.0.100/job/hfvr8apgx8st04hc/artifacts

Could you try it ?

**Comment by Omega9** [comment]
It works!

**Comment by gillesdegottex** [comment]
Great!
Now available in Version 1.0.15
