### ISSUE TITLE
Improve control file for deb packages

### ISSUE THREAD

**Issue by gillesdegottex** [gillesdegottex/fmit#49]
Installed-Size:
Description: make a list of features

**Comment by trebmuh** [comment]
Proposition for the description, [debian uses](https://anonscm.debian.org/cgit/collab-maint/fmit.git/tree/debian/control):
```
 FMIT is a graphical utility for tuning your musical instruments, with
 error and volume history and advanced features like microtonal tuning,
 statistics, and various views like waveform shape, harmonics ratios and
 real-time Discrete Fourier Transform (DFT). All views and advanced features
 are optional so that the interface can also be very simple.
```
Maybe it should be adapted since the last version shipped by debian is 1.0.0 and is then [264 commits old](https://github.com/gillesdegottex/fmit/releases/tag/v1.0.0).

**Comment by gillesdegottex** [comment]
Actually this description is already present in distrib/package_deb.control

**Comment by trebmuh** [comment]
OK, no worries. I've been pretty useless here :)
