### ISSUE TITLE
Erreur de compilation des traductions ?

### ISSUE THREAD

**Issue by trebmuh** [gillesdegottex/fmit#58]
@gillesdegottex : j'ai compilé et installé la version 1.1.11. J'ai suivi les instructions de INSTALL.TXT, et j'ai l'impression que les traductions ne sont pas compilées car je n'ai aucun fichier .qm à la fin de la compilation. À moins qu'il n'y ait une option de configuration spécifique pour cela ?
PS : pour info, je suis sur une debian Jessie à jour.

**Comment by trebmuh** [comment]
Trouvé, il fallait faire un `make lrelease` que j'ai vu en lisant https://github.com/gillesdegottex/fmit/blob/master/.travis.yml .

**Comment by gillesdegottex** [comment]
J'ai rajoute une ligne dans le INSTALL.txt pour documenter ca.
Merci!

**Comment by trebmuh** [comment]
:+1:
