### ISSUE TITLE
Tuner not working

### ISSUE THREAD

**Issue by Z1M2** [gillesdegottex/fmit#63]
The only thing that I see working is the Volume in dB green bar.
No other indication of sound.
Using W7

**Comment by gillesdegottex** [comment]
What do you mean "working is the Volume in dB green bar." It is moving when you make sounds?

**Comment by Z1M2** [comment]
Yes the Vol dB green bar moves back and forth with the sound but I see no indicatin of any to the other instruments moving or giving any indications that there is any sound.

**Comment by Z1M2** [comment]
Picking any of the choices at the top does go to the different gauges but none of them are registering   anything.

**Comment by Z1M2** [comment]
I am "trying" to learn to make Native American Fluts. I need this to learn more and set tune them.
Hoping to get it running. ?????????

**Comment by gillesdegottex** [comment]
Can you go in the settings; Sound Analysis tab; and lower the Volume threshold? (move the slider to the left)

**Comment by Z1M2** [comment]
yes lowered to 58

**Comment by gillesdegottex** [comment]
and? somehting happens now?

**Comment by Z1M2** [comment]
yes, it has gone wild.    Now all I have to do is figure out how to use it. As you can tell, never used anything like this before.

**Comment by Z1M2** [comment]
Was looking for a user manual?????

**Comment by gillesdegottex** [comment]
"User manual" ? What is that? ;)

Start simple, toggle on the first two views. Make some sounds and see how it goes. It should be intuitive enough to not need any manual.
Than you can start playing with the other views.

In your case, I would have a look at the last view (Statistics). This might be helpful to see how untuned you are on some specific notes.

**Comment by Z1M2** [comment]
It looks like it is very sensitive. It is continually jumping all over the place. Even when I play a note.

**Comment by Z1M2** [comment]
Does the same thing with the mike turned OFF.

**Comment by gillesdegottex** [comment]
So it means the recording channel is not set properly. It might try to record from your "line in" or another sound card.
Either select the proper sound card in the Settings, or change the recording channel in your OS settings (mixer, etc.)

**Comment by Z1M2** [comment]
Thanks for the help. I'll keep trying to work with it.
