### ISSUE TITLE
Problème de traduction

### ISSUE THREAD

**Issue by trebmuh** [gillesdegottex/fmit#68]
Bonjour @gillesdegottex 

Je suis en train d'empaqueter la version 1.1.13 pour la mettre dans LZK-2 et j'ai repéré un soucis quant aux traductions : il y a un "view" qui semble être ajouté dans les explications de chaque option/bouton du menu du haut.

Exemples :
![menu-view](https://user-images.githubusercontent.com/8705846/33155824-22c7331c-cff4-11e7-8be7-3fc048d0d8eb.png)

![menu-view2](https://user-images.githubusercontent.com/8705846/33155825-247d45b6-cff4-11e7-91b7-13f43b0339a0.png)

J'ai lancé fmit en allemand pour voir ("LANG=de fmit" depuis un terminal) et le problème est également présent.

Histoire d'avoir la conscience tranquille, j'ai quand même vérifié dans le fichier de traduction "fmit_fr.ts" et les "view" ne sont pas présents dedans.

Dis moi si je peux aider davantage.

**Comment by gillesdegottex** [comment]
Aie, je pense que j'ai mis ça en dur :(
Je vais tacher de corriger ........ quand je trouve du temps.
Ma foi, je pense qu'il va faloir packeter ça tel quel pour ta release car je vais pas pouvoir faire ça dans l'immediat. Est-ce que cela excluerait FMIT de ta release ?

**Comment by trebmuh** [comment]
J'ai cherché un peu plusse aujourd'hui, et j'ai trouvé où c'était.
Je te propose un correctif rapide et facile (testé et fonctionnel).
Je n'ai pas ré-ajouté "view" dans chaque chaîne de caractère car je ne suis pas certain que ça soit utile (c'est un peu redondant je trouve).

En espérant que ça aide.

PS : j'ai mis un correctif dans mon paquet pour préparer la version pour LZK-2, donc pas de soucis.

**Comment by gillesdegottex** [comment]
C'est mergé, merci!
