### ISSUE TITLE
[Feature Request] Add FMIT to Flathub.org

### ISSUE THREAD

**Issue by dsboger** [gillesdegottex/fmit#75]
It would be great if you could add FMIT to Flathub. It would mean writing and maintaining a flatkpak manifest, but then FMIT would be available on most Linux distros.

Some documentation that might be of help:

https://github.com/flathub/flathub/wiki/App-Submission
https://github.com/flathub/flathub/wiki/App-Requirements

Thanks!

**Comment by dsboger** [comment]
I've started working on a manifest myself, and it seems to be working well already. Would you mind if I pushed it to Flathub myself, and add you as a maintainer after going through the review process?

**Comment by dsboger** [comment]
Is there a way to disable the Qt capture system? I've never managed to make it work, neither in the Arch package nor in the flatpak. It seems to be forced into the build for the sake of Windows builds, is that it? 

In my experience, ALSA capture works flawlessly inside flatpak, so I would rather build the flatpak with that as the only supported capture system right now (I have no way of testing PortAudio and Jack capture for now).

**Comment by dsboger** [comment]
I've managed to remove Qt capture support by sed'ing away the line `CONFIG += acs_qt` from `fmit.pro`. Seems to be working correctly out-of-the box.

**Comment by gillesdegottex** [comment]
Hi! Thanks a lot for your time in FMIT!

This flatkpak manifest is a file that will simply end up in distrib/ ?

**Comment by gillesdegottex** [comment]
Yes, Qt capture sys is for Windows builds.

By sed'ing away this line, which capture system is used then? From the fmit.pro I can't see any other one selected by default. Or you meant that your sed replaced acs_qt by acs_alsa ?

Is alsa capture sys working on OSX too ?

I admit I never knew which capture sys we should make FMIT depends to. On Ubuntu it is alsa and jack currently. If we put the 3 alsa, jack and portaudio, it might create useless, and potentially annoying, dependencies. If we select only one out of the 4, well someone might be disappointed to not have jack or pulsaudio support ... Is there any standard strategies for this?

**Comment by trebmuh** [comment]
> someone might be disappointed to not have jack

I'm here :)

**Comment by gillesdegottex** [comment]
I see there is only one dependence on libjack* in ubuntu package, so let's try to keep jack in the default build :)

**Comment by trebmuh** [comment]
Thank you!

**Comment by dsboger** [comment]
> This flatkpak manifest is a file that will simply end up in distrib/ ?

A flatpak manifest would enable anyone to build the flatpak bundle in a reproducible, host-independent way, which great in itself. But flathub goes beyond that, being an actual "store" that hosts the manifests, builds them and serves the resulting flatpak bundles.

https://github.com/flathub/flathub/wiki/App-Submission explains a bit how flathub works. It is intended that app developers themselves should maintain the manifests on flathub, just like they do on e.g. Play Store apps. But that is not a strong requirement, especially for open source apps.

**Comment by dsboger** [comment]
About the capture systems, I remove `acs_qt` (sed'ing `fmit.pro`) and add `acs_alsa` (through an argument passed to `qmake`).

The problem with other capture systems is how they will be handled in the sandbox (i.e. how the FMIT code will communicate with the audio server in the host). Currently, flatpak sandbox (i.e. bubblewrap) supports PulseAudio and the sandboxed ALSA seems to use that. I don't know if JACK can be made to work right now, but if so there is no reason not to include acs_jack. On the other hand, if the sandbox currently does not support JACK, I think it will not make sense to include a non-working acs_jack. The same goes for PortAudio.

**Comment by dsboger** [comment]
> Is alsa capture sys working on OSX too ?

No idea, but flatpak does not work on OSX either, so I guess it does not matter here.

**Comment by gillesdegottex** [comment]
Ok for flathub, go one and submit.

**Comment by gillesdegottex** [comment]
If I understand properly, if you do this flatpak stuff we will lose jack in the default build ?

**Comment by dsboger** [comment]
Yes, the flatpak build hosted on flathub will not support jack, but that won't affect traditional distro packages at all. Maybe I was not clear, but flatpak/flathub is an alternative way to get apps. It has several advantages, but users are not required to use it. If they prefer to keep using their distro package, nothing will change for them.

I've tried to make acs_jack to work in the sandbox but without success until now. I've opened https://github.com/flatpak/flatpak/issues/1509 to try to find a solution with the flatpak devs.

@gillesdegottex would you rather wait for a possible solution, or could we just go with acs_alsa alone for now and enable acs_jack later?

**Comment by gillesdegottex** [comment]
Well if the Debian/Ubuntu packages will keep the jack support, yes, go ahead and submit on flathub.

**Comment by dsboger** [comment]
I've submitted the flatpak manifest: https://github.com/flathub/flathub/pull/314

**Comment by gillesdegottex** [comment]
Thanks!

**Comment by dsboger** [comment]
Looks like the submitted flatpak was successfully built by flathub servers.

Would it be possible to do a point release so the improvements in the AppData are in a stable release?

**Comment by gillesdegottex** [comment]
done.

**Comment by dsboger** [comment]
FMIT is on flathub! You may check https://beta.flathub.org/apps/details/io.github.gillesdegottex.FMIT for details and installation instructions. Now I'm making some tests to enable acs_jack.

**Comment by dsboger** [comment]
Current build on flathub now has acs_jack enabled. It seems to work for me.

@trebmuh Could you test if the current build on flathub works for you with JACK?

**Comment by trebmuh** [comment]
@dsboger : would you have a step-by-step procedure for me to test? Never did that before.

**Comment by dsboger** [comment]
There are instructions at the bottom of [this page](https://beta.flathub.org/apps/details/io.github.gillesdegottex.FMIT). I personally find it easier on the command line. You could try something like (under Debian/Ubuntu/Mint/etc.):

```
$ sudo apt install flatpak
$ flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
$ flatpak install flathub io.github.gillesdegottex.FMIT
```

It will not affect your system packages at all. Depending on your desktop environment, the app icon might not appear in the menu, because flatpak does not install the desktop file in the standard location as to not interfere with the system. In any case, you can run the app using the command line also:

```
$ flatpak run io.github.gillesdegottex.FMIT
```

It should work with the JACK daemon in the host system.

**NOTE**: flatpak will download and install a few runtimes (freedesktop and KDE), so it may take a little while for your first app. These runtimes also do not interfere with host system packages.

**Comment by dsboger** [comment]
@trebmuh How you given this a try? I'd like to close this issue if JACK is working for you, or try another fix otherwise.

**Comment by trebmuh** [comment]
@dsboger : I've tested the FMIT flatpak installation and it successfully works with JACK. Thanks for the reminder.

**Comment by dsboger** [comment]
@trebmuh Excellent! Thank you for testing! 

I'm closing this then. I'll keep maintaining the flathub repo and keep monitoring issues here in case something flatpak-related is reported. I'll also stop maintaining the Arch's AUR packages ([fmit](https://aur.archlinux.org/packages/fmit/) and [fmit-git](https://aur.archlinux.org/packages/fmit-git/)), since I won't be using/testing them anymore. Let's hope someone else steps up and adopts them.

**Comment by BrunoVernay** [comment]
The Jack tab is displayed in FMIT, but I does NOT seem to be functional. FMIT does NOT show up in Jack.
At least on Fedora 29. (I also tried MuseScore with Jack, with device=all,  and it did not work.) 
I would love to have it working. If someone has a functional installation I would be really curious!
