### ISSUE TITLE
1.1.4 : wrong changelog items

### ISSUE THREAD

**Issue by trebmuh** [gillesdegottex/fmit#83]
Looks like some of the changelog items have been (wrongly) copied/pasted from the last 1.1.4 changelog. See https://github.com/gillesdegottex/fmit/releases and compare to https://github.com/gillesdegottex/fmit/compare/v1.1.13...v1.1.14

**Comment by gillesdegottex** [comment]
I always do this when I only change the revision number.

**Comment by trebmuh** [comment]
OK, I didn't noticed that before.
