### ISSUE TITLE
Update screenshots

### ISSUE THREAD

**Issue by dsboger** [gillesdegottex/fmit#85]
Hi, the screenshots in the website (also used by Flathub) are starting to look outdated (e.g. window decorations, icons). Also, some of the screenshots are a missing a bit of context, like those showing some views cut away from the window.

I took some screenshots in my system and tried to follow the [appstream guidelines](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#qsr-app-screenshots-info) also for a better presentation in Flathub. [fmit-screenshots.zip](https://github.com/gillesdegottex/fmit/files/1939360/fmit-screenshots.zip)

If you like those, you can replace the old ones in the website (and maybe add the new ones showing the settings panels). After that I can do a PR changing the appstream file with links to the new images.

Thanks!

**Comment by dsboger** [comment]
Fixed a few screenshots that showed an unfocused preferences window.

[fmit-screenshots-2.zip](https://github.com/gillesdegottex/fmit/files/1953551/fmit-screenshots-2.zip)

**Comment by gillesdegottex** [comment]
I updated the ss.
Do you mind redoing simple.png, in a narrower format? (as the original was, e.g.) It shows that the user can scale the format a bit however they want, and it's not a fixed format.

**Comment by dsboger** [comment]
Ok. I've taken a narrow simple.png, but I've kept the old 16:9 one as simple-2.png. Could you keep both (even if not shown in the site)? Also, I noticed in the page that settings-capture.png is doubled while settings-general.png is missing.

[fmit-screenshots-3.zip](https://github.com/gillesdegottex/fmit/files/1962174/fmit-screenshots-3.zip)

**Comment by gillesdegottex** [comment]
Updated, added and fixed.
Thanks a lot!
