### ISSUE TITLE
Possible terminology issue with "Tonality"

### ISSUE THREAD

**Issue by dsboger** [gillesdegottex/fmit#90]
I'm trying to better understand the inner workings of FMIT (and music theory/sound analysis in the process) and stumbled upon something: the term Tonality seems to be used differently from its [usual definitions](https://en.wikipedia.org/wiki/Tonality). 

From what I could understand, what FMIT calls Tonality is some "transposition trick" so that, for example, a player used to a soprano recorder (C) can play an alto recorder (F) and see the same note names for the same fingering. 

If my assumption is correct, it would maybe be more correct to use "Transposition". What do you think?

**Comment by gillesdegottex** [comment]
Indeed, seems wrong. I'm asking a good musician friend who knows about those things better.

**Comment by gillesdegottex** [comment]
"Transposition" or "Transposition key" seem good.
It's fun to see that even the wikipedia pages are not able to find a constant and specific term for this.

**Comment by dsboger** [comment]
Fixed by 837433d852e3650da4c197ee2fe6aa62c36d1a9d. Closing.
