### ISSUE TITLE
PR not properly checked

### ISSUE THREAD

**Issue by gillesdegottex** [gillesdegottex/fmit#92]
See comments in #91 and:
```
$ git checkout $TRAVIS_BRANCH
Warning: you are leaving 2 commits behind, not connected to
any of your branches:
  272f5e1 Merge 56f615d2389503d0e765da2f42d439bcbe350ebc into b8e3d8f7d110d5ae891576c99dd99e9610017cf1
  56f615d Convert QGLWidget usage to QOpenGLWidget
If you want to keep them by creating a new branch, this may be a good time
to do so with:
 git branch <new-branch-name> 272f5e1
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
```

**Comment by dsboger** [comment]
Is that explicit git checkout necessary? Should not Travis prepare the repository automatically?

**Comment by gillesdegottex** [comment]
Yes it should, but I had to do this for .... for a reason I can't remember now :P

**Comment by gillesdegottex** [comment]
I think the describe was not working properly.
Let's try without.

**Comment by dsboger** [comment]
When I checkout from v1.1.18, then compile and run FMIT, the about dialog shows "Version 1.1.18-HEAD". Is that what you mean?

**Comment by gillesdegottex** [comment]
yes, that was the bug this checkout was dealing with.
travis checkout the commit in a detached head (don't ask me why, I've never really understood)
now we need a fix that deals with both situations ...
