### ISSUE TITLE
Issue with translation

### ISSUE THREAD

**Issue by trebmuh** [gillesdegottex/fmit#99]
Following https://github.com/gillesdegottex/fmit/pull/98

@gillesdegottex , j'ai fait une construction avec cette rustine et le dialogue "à propos de FMIT ..." ->  "Crédit" reste en anglais. Et je ne comprends pas pourquoi après avoir regardé autour.

Je ne sais pas si c'est lié ou pas, mais j'ai remarqué qu'il y a cette ligne affichée dans la fenêtre "Crédit" : " dsboger for so many little and usefull changes, updates, packaging, etc" qui ne figure pas dans le fichier de traduction.

**Comment by dsboger** [comment]
Some recent commits changed some strings, so the translation files are a bit outdated. I'll make a commit for the updated translations soon (after which I'll also update the Flathub version).

By the way, FMIT advertises [this](https://www.transifex.com/fmit/free-music-instrument-tuner-fmit/) Transifex project as its translation site. The strings there are also a bit outdated, but I'll update those soon. Even if it is easy to propose a PR with translation improvements/fixes (and I've done that in the past too), it makes the management of the Transifex project much harder.

I think it would be best if we could agree to a single workflow by either:

- Going Transifex: promote it more prominently (e.g. in the README), then point translation PR authors to the site. I can update the strings whenever there is a change and @gillesdegottex could pull the most recent translations right before releasing.
- Dropping Transifex: forget about it and promote translation PRs. It would remove a maintenance burden, but also dismiss an accessible platform that could bring more contributors.

@gillesdegottex, what do you think?

**Comment by trebmuh** [comment]
I dislike transifex. What about weblate ?
Keeping doing PR is fine as well for me.

**Comment by trebmuh** [comment]
> Some recent commits changed some strings, so the translation files are a bit outdated. I'll make a commit for the updated translations soon (after which I'll also update the Flathub version).

Are the translation files regenerated before each new release?

> ... re: transifex or not

I dislike transifex. What about weblate ?
Keeping doing PR is fine as well for me.

**Comment by dsboger** [comment]
> Are the translation files regenerated before each new release?

@gillesdegottex is releasing very eagerly :). But also after translation updates, so I'm not too worried about that. We can just update translations and a new release will come soon after that.

> I dislike transifex. What about weblate ?
> Note that keeping doing PR is fine as well (for me).

Weblate is also very nice, and it has automatic integration with GitHub (i.e. it will pull/push directly). I will support any option, but it would be best if we agree on a single one, to simplify maintenance.

**Comment by gillesdegottex** [comment]
I just had a quick look at weblate, but I didn't see how to integrate it quickly to a github project.
I've oppened an account on weblate, though my projects don't appear somewhere and I've added weblate as service in fmit, though I don't see any consequence of it.
Any pointer ?

**Comment by dsboger** [comment]
I think you need to ask for free hosting for a free software project. Check [this](https://weblate.org/hosting/#free) page. It also has some explanations/pointers about GitHub integration.

**Comment by gillesdegottex** [comment]
Weblate might be good and better than Transifex, but I don't really have time to do more than hitting a few buttons to activate a new services ... Is it really a problem to stay on Transifex ?

**Comment by dsboger** [comment]
@gillesdegottex I'm OK with helping to maintain translations on Transifex (i.e. push new strings from GitHub to Transifex, open PRs here when translations evolve in Transifex). But it becomes very burdensome if I have to merge parallel changes from both GitHub and Transifex. So, if the decision is to keep Transifex, direct PRs with translations should be rejected (with a polite message pointing to Transifex :).

**Comment by gillesdegottex** [comment]
Ok, I got it now. So let's do it this way. I'm happy with advertising Transifex FMIT page everywhere necessary with a few lines of instructions.

**Comment by gillesdegottex** [comment]
And Thanks @dsboger !!!

**Comment by trebmuh** [comment]
(For the record) I'll not be able to contribute translation anymore to FMIT. You'll have to handle those @gillesdegottex (or someone else).

**Comment by gillesdegottex** [comment]
*Ouch*, Transifex is so bad ? :)
Do you mind describing the problem/bottleneck/issue with it ?

**Comment by trebmuh** [comment]
Mainly (if I'm not wrong and I reckon correctly), Transifex isn't free software at all. Weblate is.

**Comment by gillesdegottex** [comment]
Oh, indeed, it is ...

**Comment by gillesdegottex** [comment]
@trebmuh @dsboger 
I'll dig a bit more on Weblate to see how goes the integration, bcs I could use it for other softwares actually.
So let's pause on this decision for now and let's take it by the end of the week, the latest.

**Comment by gillesdegottex** [comment]
Included in Weblate:
https://hosted.weblate.org/projects/fmit/

**Comment by gillesdegottex** [comment]
I still have to understand how it works and setup the auto pull/push.

**Comment by trebmuh** [comment]
No worries. I've made a few translations on weblate, then you can experiment with that. Don't be afraid if something gets lost while doing it, it didn't took me more than 10 minutes, then I can redo those quickly.

**Comment by dsboger** [comment]
Weblate docs:

Making Weblate auto-pull changes: https://docs.weblate.org/en/latest/admin/continuous.html#github-setup

Making Weblate auto-push translations: https://docs.weblate.org/en/latest/admin/continuous.html#hosted-push

**Comment by gillesdegottex** [comment]
Let's try with this Weblate.
I've set things up (or I did it properly I hope). The auto-push system still needs to be acknowledged on Weblate's side though.

**Comment by dsboger** [comment]
Great! I'll announce on Transifex site that translations have moved.

By the way :), now that #100 is merged, could you also add appdata.pot to the Weblate site?

**Comment by gillesdegottex** [comment]
> could you also add appdata.pot to the Weblate site?

I've strictly no clue how this is done as the Weblate manager did everything for us. I don't even see a "add file" option or something like that.

**Comment by dsboger** [comment]
The [docs](https://docs.weblate.org/en/latest/admin/projects.html#component) are not explicit about how to add files, but from what I could understand, they are called Components, if that is of any help.

**Comment by dsboger** [comment]
Found another bit of [documentation](https://docs.weblate.org/en/latest/admin/projects.html#adding-new-components).

**Comment by dsboger** [comment]
AppData translation is working! IMO, this issue is fixed. Thanks for your efforts!

**Comment by trebmuh** [comment]
All of this thread is really nice! Thanks guys!
:+1:
